name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          # `.terraform-version` で指定されたバージョンを使用する
          terraform_version: $(head -n 1 .terraform-version)
      - name: Run Terraform Format
        run: terraform fmt --diff --recursive
  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.56.0

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: |
          tflint --chdir=environments/staging --config=$(realpath .tflint.hcl) --format compact
          tflint --chdir=environments/production --config=$(realpath .tflint.hcl) --format compact
        env:
          GITHUB_TOKEN: ${{ github.token }}
